In [5]:
import pandas as pd
left = pd.DataFrame(
    {
        "key":["K0", "K1", "K2", "AЗ"],
        "Α": ["Α0", "Α1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
    }
)

right = pd.DataFrame(
    {
       "key": ["K0", "К1", "K2", "К3"],
       "C": ["C0", "C1", "C2", "C3"],
       "D": ["D0", "D1", "D2", "D3"],
    }
)

result = pd.merge(left, right, on="key")

result

  key   Α   B   C   D
0  K0  Α0  B0  C0  D0
1  K2  A2  B2  C2  D2

In [12]:
left=pd.DataFrame(
{
"key": ["K0", "K1", "K2", "A3"],
"A": ["A0", "A1", "A2", "A3"],
"B":["B0", "B1", "B2", "B3"],
}
)

right=pd.DataFrame(
{
"key": ["K0", "K1", "K2", "K3"],
"C": ["C0", "C1", "C2", "C3"],
"D": ["D0", "D1", "D2", "D3"],
}
)

result = pd.merge(left, right, on="key")

result

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2

In [8]:
left=pd.DataFrame(
{
"key1": ["K0", "K0", "K1", "K2"],
"key2": ["K0", "K1", "K0", "К1"],
"A": ["A0", "A1", "A2", "A3"],
"B":["B0", "B1", "B2", "B3"],
}
)

right=pd.DataFrame(
{
"key1": ["K0", "K1", "K1", "K2"],
"key2": ["K0", "K0", "K0", "K0"],
"C": ["C0", "C1", "C2", "C3"],
"D": ["D0", "D1", "D2", "D3"],
}
)

result = pd.merge(left, right, how="left", on=["key1", "key2"])

result

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   К1  A3  B3  NaN  NaN

In [9]:
result = pd.merge(left, right, how="right", on=["key1", "key2"])
result

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [10]:
result = pd.merge(left, right, how="outer", on=["key1", "key2"])
result

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   К1   A3   B3  NaN  NaN

In [11]:
result = pd.merge(left, right, how="inner", on=["key1", "key2"])
result

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2