<a href="https://colab.research.google.com/github/springboardmentorLive/Reality_AI/blob/ananyarohidasshet/IS_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.	Write a Python program that performs the following tasks:
data = {
    'Name': ['Riya', 'Karan', None, 'Meena', 'Amit', None, 'Sneha', 'Vikas', 'Neha', 'Tina'],
    'Age': [28, 30, 22, None, 26, 21, None, 24, 29, None],
    'Gender': ['F', 'M', 'M', 'F', 'M', 'M', 'F', 'M', 'F', 'F'],
    'Score': [91, None, 76, 84, 89, 95, None, 88, 93, 90]
}
•	Store this dataset into a CSV file named raw_data.csv.
•	Read the first 5 rows of the data from raw_data.csv using pandas.
•	Drop rows with any missing values.
•	Count the number of missing values in each column.
•	Fill missing values in the Name column with "some name" and in the Age column with 21.
•	Save the cleaned dataset into a new CSV file named cleaned_data.csv.

In [ ]:
import pandas as pd

data = {
    'Name': ['Riya', 'Karan', None, 'Meena', 'Amit', None, 'Sneha', 'Vikas', 'Neha', 'Tina'],
    'Age': [28, 30, 22, None, 26, 21, None, 24, 29, None],
    'Gender': ['F', 'M', 'M', 'F', 'M', 'M', 'F', 'M', 'F', 'F'],
    'Score': [91, None, 76, 84, 89, 95, None, 88, 93, 90]
}

df = pd.DataFrame(data)
df.to_csv('raw_data.csv', index=False)

In [ ]:
df.dropna()

    Name   Age Gender  Score
0   Riya  28.0      F   91.0
4   Amit  26.0      M   89.0
7  Vikas  24.0      M   88.0
8   Neha  29.0      F   93.0

In [ ]:
df.isnull().sum()

Name      2
Age       3
Gender    0
Score     2
dtype: int64

In [ ]:
cleaned_df = df.copy()

cleaned_df["Name"].fillna("Anshu", inplace=True)
cleaned_df["Age"].fillna(21,inplace=True)
cleaned_df

/tmp/ipython-input-1936749780.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned_df["Name"].fillna("Anshu", inplace=True)
/tmp/ipython-input-1936749780.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned_df["Age"].fillna(21,inplace=True)

    Name   Age Gender  Score
0   Riya  28.0      F   91.0
1  Karan  30.0      M    NaN
2  Anshu  22.0      M   76.0
3  Meena  21.0      F   84.0
4   Amit  26.0      M   89.0
5  Anshu  21.0      M   95.0
6  Sneha  21.0      F    NaN
7  Vikas  24.0      M   88.0
8   Neha  29.0      F   93.0
9   Tina  21.0      F   90.0

In [ ]:
cleaned_df.to_csv("cleaned_data.csv")